In [1]:
import pandas as pd
import numpy as np

from matplotlib import pyplot as plt

In [2]:
# load the provided data
train_features = pd.read_csv(
    "../data/raw/dengue_features_train.csv", index_col=[0, 1, 2]
)

train_labels = pd.read_csv(
    "../data/raw/dengue_labels_train.csv", index_col=[0, 1, 2]
)

In [3]:
# Seperate data for San Juan
sj_train_features = train_features.loc["sj"]
sj_train_labels = train_labels.loc["sj"]

# Separate data for Iquitos
iq_train_features = train_features.loc["iq"]
iq_train_labels = train_labels.loc["iq"]

In [4]:
print("San Juan")
print("features: ", sj_train_features.shape)
print("labels  : ", sj_train_labels.shape)

print("\nIquitos")
print("features: ", iq_train_features.shape)
print("labels  : ", iq_train_labels.shape)

San Juan
features:  (936, 21)
labels  :  (936, 1)

Iquitos
features:  (520, 21)
labels  :  (520, 1)


In [5]:
# Remove `week_start_date` string.
sj_train_features.drop("week_start_date", axis=1, inplace=True)
iq_train_features.drop("week_start_date", axis=1, inplace=True)

C:\Users\user\AppData\Local\Temp\ipykernel_15756\3954673652.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sj_train_features.drop("week_start_date", axis=1, inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_15756\3954673652.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iq_train_features.drop("week_start_date", axis=1, inplace=True)


In [6]:
sj_train_features.isna().sum()

ndvi_ne                                  191
ndvi_nw                                   49
ndvi_se                                   19
ndvi_sw                                   19
precipitation_amt_mm                       9
reanalysis_air_temp_k                      6
reanalysis_avg_temp_k                      6
reanalysis_dew_point_temp_k                6
reanalysis_max_air_temp_k                  6
reanalysis_min_air_temp_k                  6
reanalysis_precip_amt_kg_per_m2            6
reanalysis_relative_humidity_percent       6
reanalysis_sat_precip_amt_mm               9
reanalysis_specific_humidity_g_per_kg      6
reanalysis_tdtr_k                          6
station_avg_temp_c                         6
station_diur_temp_rng_c                    6
station_max_temp_c                         6
station_min_temp_c                         6
station_precip_mm                          6
dtype: int64

In [7]:
sj_train_features.fillna(method="ffill", inplace=True)
iq_train_features.fillna(method="ffill", inplace=True)

C:\Users\user\AppData\Local\Temp\ipykernel_15756\2559599374.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  sj_train_features.fillna(method="ffill", inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_15756\2559599374.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sj_train_features.fillna(method="ffill", inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_15756\2559599374.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  iq_train_features.fillna(method="ffill", inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_15756\2559599374.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy

In [9]:
# sj_train_features.isna().sum()
# iq_train_features.isna().sum()


In [11]:
sj_train_features.head()

ndvi_ne   ndvi_nw   ndvi_se   ndvi_sw  precipitation_amt_mm  \
year weekofyear                                                                 
1990 18          0.122600  0.103725  0.198483  0.177617                 12.42   
     19          0.169900  0.142175  0.162357  0.155486                 22.82   
     20          0.032250  0.172967  0.157200  0.170843                 34.54   
     21          0.128633  0.245067  0.227557  0.235886                 15.36   
     22          0.196200  0.262200  0.251200  0.247340                  7.52   

                 reanalysis_air_temp_k  reanalysis_avg_temp_k  \
year weekofyear                                                 
1990 18                     297.572857             297.742857   
     19                     298.211429             298.442857   
     20                     298.781429             298.878571   
     21                     298.987143             299.228571   
     22                     299.518571             299.664286   

                 reanalysis_dew_point_temp_k  reanalysis_max_air_temp_k  \
year weekofyear                                                           
1990 18                           292.414286                      299.8   
     19                           293.951429                      300.9   
     20                           295.434286                      300.5   
     21                           295.310000                      301.4   
     22                           295.821429                      301.9   

                 reanalysis_min_air_temp_k  reanalysis_precip_amt_kg_per_m2  \
year weekofyear                                                               
1990 18                              295.9                            32.00   
     19                              296.4                            17.94   
     20                              297.3                            26.10   
     21                              297.0                            13.90   
     22                              297.5                            12.20   

                 reanalysis_relative_humidity_percent  \
year weekofyear                                         
1990 18                                     73.365714   
     19                                     77.368571   
     20                                     82.052857   
     21                                     80.337143   
     22                                     80.460000   

                 reanalysis_sat_precip_amt_mm  \
year weekofyear                                 
1990 18                                 12.42   
     19                                 22.82   
     20                                 34.54   
     21                                 15.36   
     22                                  7.52   

                 reanalysis_specific_humidity_g_per_kg  reanalysis_tdtr_k  \
year weekofyear                                                             
1990 18                                      14.012857           2.628571   
     19                                      15.372857           2.371429   
     20                                      16.848571           2.300000   
     21                                      16.672857           2.428571   
     22                                      17.210000           3.014286   

                 station_avg_temp_c  station_diur_temp_rng_c  \
year weekofyear                                                
1990 18                   25.442857                 6.900000   
     19                   26.714286                 6.371429   
     20                   26.714286                 6.485714   
     21                   27.471429                 6.771429   
     22                   28.942857                 9.371429   

                 station_max_temp_c  station_min_temp_c  station_precip_mm  
year weekofyear                                                             
1990 18                    

In [ ]:
# sj_train_features.reset_index(inplace=True)
# iq_train_features.reset_index(inplace=True)

In [24]:
sj_train_labels.shape

(936, 1)

In [ ]:
X_sj= sj_train_features
y_sj = sj_train_labels["total_cases"]

X_iq= iq_train_features
y_iq = iq_train_labels["total_cases"]

In [22]:
from sklearn import linear_model
from sklearn.model_selection import cross_validate
from sklearn.metrics import make_scorer
from sklearn.metrics import confusion_matrix
from sklearn.metrics import mean_squared_error
lasso = linear_model.Lasso()

In [28]:
scores_sj = cross_validate(lasso, X_sj, y_sj, cv=3,
                        scoring=('r2', 'neg_mean_squared_error'),
                        return_train_score=True)
print(scores_sj['test_neg_mean_squared_error'])
[-3635.5 -3573.3 -6114.7]
print(scores_sj['train_r2'])

[-5771.72376942 -1546.75051271 -1202.10625698]
[0.1498631  0.0548679  0.06488114]


In [29]:
scores_iq = cross_validate(lasso, X_iq, y_iq, cv=3,
                        scoring=('r2', 'neg_mean_squared_error'),
                        return_train_score=True)
print(scores_iq['test_neg_mean_squared_error'])
[-3635.5 -3573.3 -6114.7]
print(scores_iq['train_r2'])

[ -71.94310176 -147.63698159 -134.71929308]
[0.03517521 0.07629327 0.07057754]
